QT.pdf.VERSION = 5.15.11
QT.pdf.name = QtPdf
QT.pdf.module = QtPdf
QT.pdf.libs = $$QT_MODULE_LIB_BASE
QT.pdf.includes = $$QT_MODULE_LIB_BASE/QtPdf.framework/Headers
QT.pdf.frameworks = $$QT_MODULE_LIB_BASE
QT.pdf.bins = $$QT_MODULE_BIN_BASE
QT.pdf.depends = core gui
QT.pdf.run_depends = network
QT.pdf.uses =
QT.pdf.module_config = v2 lib_bundle
QT.pdf.DEFINES = QT_PDF_LIB
QT.pdf.enabled_features =
QT.pdf.disabled_features =
QT_CONFIG +=
QT_MODULES += pdf
